(function(){ var aa=window.PATH_ROOT_WEB&&"string"===typeof window.PATH_ROOT_WEB&&0<window.PATH_ROOT_WEB.length?window.PATH_ROOT_WEB:"https://1plus1.video/",d=window._opov instanceof Array&&0<window._opov.length?window._opov:[],h=document.cookie.match(new RegExp("(?:^|; )"+"_opov_hid_l".replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)"));h&&decodeURIComponent(h[1].replace(/\+/g,"%20"));var m=window.CURRENT_LANGUAGE||"ua";
function n(a){if("undefined"===typeof a||0<arguments.length){for(var b=0;b<arguments.length;b++)if(arguments[b]="number"===typeof arguments[b]?arguments[b].toString():arguments[b],!("string"===typeof arguments[b]&&0<arguments[b].length))return!1;return!0}return!1}
function r(a){if("string"===typeof a&&(3===a.length||6<=a.length)){var b=/^#?([a-f\d])([a-f\d])([a-f\d])$/i;3===a.length&&(a=a.replace(b,function(c,e,f,g){return e+e+f+f+g+g}));return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a.substr(0,6)))?{r:parseInt(a[1],16),l:parseInt(a[2],16),b:parseInt(a[3],16)}:null}return null}function t(a){if("object"===typeof a)for(var b in a)return!0;return!1}
function v(a){var b={},c="Boolean Number String Function Array Date RegExp Object Error Symbol Arguments HTMLCollection CSSRuleList".split(" "),e=b.toString;if(!t(b))for(var f=0;f<c.length;f++)b["[object "+c[f]+"]"]=c[f].toLowerCase();return null===a?a+"":"object"===typeof a||"function"===typeof a?b[e.call(a)]||"object":typeof a}function w(a){return null!==a&&"object"===typeof a?(Array.isArray||function(b){return b instanceof Array})(a):!1}function y(a){return w(a)&&t(a)}
function z(a){return a&&(a instanceof HTMLElement||a instanceof Document||a instanceof Window)}function A(a){if(z(a))try{a.parentNode.removeChild(a)}catch(b){}}function B(a){if(z(a)&&0<a.childNodes.length)for(;a.firstChild;)a.removeChild(a.firstChild)}
function C(a,b){var c=/[\t\r\n\f]/g,e=/\S+/g;if(z(a))if("object"===typeof a.classList&&"function"===typeof a.classList.add)if(-1!==b.indexOf(" ")){if(b=b.split(" "))for(c=0;c<b.length;c++)a.classList.add(b[c])}else a.classList.add(b);else{var f;if(n(b)&&(b=(b||"").match(e)||[],c=1===a.nodeType&&(a.className?(" "+a.className+" ").replace(c," "):" "))){for(f=0;e=b[f++];)0>c.indexOf(" "+e+" ")&&(c+=e+" ");b=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;b=n(c)?"function"===typeof String().trim?c.trim():(c+"").replace(b,
""):"";a.className!==b&&(a.className=b)}}}function ba(a){var b=/[\t\r\n\f]/g;return z(a)?"object"===typeof a.classList&&"function"===typeof a.classList.contains?a.classList.contains("api-gpt-fixed"):1===a.nodeType&&0<=(" "+a.className+" ").replace(b," ").indexOf(" api-gpt-fixed "):!1}
function D(a,b,c,e){if(z(a)){b=b.toLowerCase();if(!0===e){var f=c;c=function(p){E(a,b,c);return f.apply(this,arguments)}}a.attachEvent?(a["e"+b+c]=c,a[b+c]=function(){a["e"+b+c](window.event)},a.attachEvent("on"+b,a[b+c])):a.addEventListener(b,c,!1)}else if(w(a))for(var g in a)a.hasOwnProperty(g)&&z(a[g])&&D(a[g],b,c,e)}
function E(a,b,c){if(z(a))b=b.toLowerCase(),a.detachEvent?(a.detachEvent("on"+b,a[b+c]),a[b+c]=null):a.removeEventListener(b,c,!1);else if(w(a))for(var e in a)a.hasOwnProperty(e)&&z(a[e])&&E(a[e],b,c)}
function F(a,b,c,e){function f(){q();"function"===typeof e&&e.call(null)}function g(){q();"function"===typeof c&&c.call(null,k||b)}function p(){f()}function q(){E(l,"load",g);E(l,"error",p)}var k=null,l=document.createElement("script");var x={};x.src=a;for(var u in x)x.hasOwnProperty(u)&&l.setAttribute(u,x[u]);if(n(a)&&z(b))if(l){D(l,"load",g,!1);D(l,"error",p,!1);try{b instanceof HTMLIFrameElement?k=b.contentWindow:b instanceof Window&&(k=b),z(null!==k&&"object"===typeof k.document&&9===k.document.nodeType?
k.document.body.appendChild(l):b.appendChild(l))||f()}catch(I){f()}}else f();else f()}function G(){for(var a=[],b=0;36>b;b++)a[b]="0123456789abcdef".substr(Math.floor(16*Math.random()),1);a[14]="4";a[19]="0123456789abcdef".substr(a[19]&3|8,1);a[8]=a[13]=a[18]=a[23]="-";return a.join("")}
var H="https://www.googletagservices.com/tag/js/gpt.js?_t="+(Date.now||function(){return+new Date})(),J={catfish:[[980,120],[320,50],[320,100],[320,165],[468,60],[728,90],[1350,180],[1440,180]]},K={catfish:[[[730,0],[[1440,180],[980,120],[728,90]]],[[0,0],[[320,100],[320,50]]]],catfish_2:[[[1440,0],[1440,180]],[[1350,0],[1350,180]],[[980,0],[980,120]],[[728,0],[728,90]],[[468,0],[468,60]],[[0,0],[[320,50],[320,100],[320,165]]]]},L={TYPE:"gpt",GPT_ID:null,GPT_DATA_LAYER:!1,CLASS:null,CENTERING:!0,
CLEAR_NODE:!0,GPT:null,BEFORE_SCRIPT:null},M={"class":{type:"object",i:"CLASS"},gpt:{type:"object",i:"GPT"},gpt_id:{type:"string",i:"GPT_ID"},gpt_dataLayer:{type:"boolean",i:"GPT_DATA_LAYER"},gpt_bf:{type:"string",i:"BEFORE_SCRIPT"}},N=L.TYPE,O=!1;O="boolean"===typeof O?O:!1;
if(y(d)&&t(M)&&n(N)){var P=[],Q;for(Q in M)M.hasOwnProperty(Q)&&(P.push(Q),"undefined"===typeof M[Q].type&&(M[Q].type="string"));for(var R=0;R<d.length;R++)if(t(d[R])&&"string"===typeof d[R].type&&d[R].type===N){for(var S=0;S<P.length;S++)if(null!==P[S]&&"undefined"!==typeof d[R][P[S]]){if(typeof d[R][P[S]]===M[P[S]].type)switch(M[P[S]].type){case "string":0<d[R][P[S]].length&&(L[M[P[S]].i]=d[R][P[S]]);break;case "number":L[M[P[S]].i]=d[R][P[S]];break;case "object":L[M[P[S]].i]=d[R][P[S]];break;case "boolean":L[M[P[S]].i]=
"1"===d[R][P[S]]||"true"===d[R][P[S]]||!0===d[R][P[S]]}O&&(P[S]=null)}if(O)for(S=0;S<P.length;S++)if(null===P[S]){var T=P,U=S;U=parseInt(U,10);var V;if(V=w(T)&&"number"===typeof U)V="undefined"!==typeof T[U];V&&T.splice(U,1)}}}var ca=document.body||document.getElementsByTagName("body")[0],da=!1,ea=!1,W=!1,fa=0,X;
function ha(a){function b(){W?clearInterval(X):100>500*fa?fa++:c()}function c(){clearInterval(X);F("https://gaua.hit.gemius.pl/xgemius.js",document.getElementsByTagName("head")[0],null,function(){if(!W)for(var e in a)if(a.hasOwnProperty(e)&&z(a[e].node)){var f=a[e].node;B(f);f.style.display="block";f.removeAttribute("id");var g=document.createElement("iframe");g.src=aa+("ua"!==m?"/"+m:"")+"/ab/";g.width="100%";g.height="100%";g.setAttribute("scrolling","no");g.setAttribute("frameborder","0");g.setAttribute("allowtransparency",
"true");parseInt(f.offsetWidth,10)>parseInt(f.offsetHeight,10)&&C(g,"horizontal");f.appendChild(g)}})}a&&(W&&(da||ea)||(X=setInterval(b,500)))}
function ia(){function a(){ja(function(){if(n(L.CLASS)){var b=document.getElementsByClassName(L.CLASS);if(b&&b instanceof HTMLCollection&&0<b.length){L.GPT=L.GPT||[];for(var c=0;c<b.length;c++){var e=b[c];if(e.hasAttribute("data-path")&&e.hasAttribute("data-size")&&n(e.getAttribute("data-path"))&&n(e.getAttribute("data-size"))){var f=e.id?e.id:e.id=L.TYPE+"-"+G(),g=e.getAttribute("data-path");var p=e.clientWidth;var q=e.clientHeight;switch(e.getAttribute("data-size")){case "target":p=p&&q?[p,q]:null;
break;case "fluid":p="fluid";break;case "catfish":p=J.m;break;default:p=JSON.parse(e.getAttribute("data-size")),p="array"===v(p)?p:null}if(f&&p&&g){q=e.getAttribute("data-mapping");switch(q){case "catfish":q=K.m;break;default:q=(q=JSON.parse(e.getAttribute("data-mapping")))&&"array"===v(q)&&0<q.length?q:null}var k=JSON.parse(e.getAttribute("data-targeting"));k=k&&"array"===v(k)&&0<k.length?k:null;var l=parseInt(e.getAttribute("data-close"),10);l=1===l||2===l?l:null;var x=e.getAttribute("data-bg");
x=x&&n(x)?x:null;var u=e.getAttribute("data-bg-opacity");u=u&&n(u)?u:null;u=0<=u&&1>=u?u:null;e=(e=e.getAttribute("data-border"))&&n(e)?e:null;L.GPT.push({id:f,path:g,size:p,mapping:q?q:null,targeting:k?k:null,close:l?l:null,bg:x?x:null,bg_opacity:u?u:null,border:e?e:null})}}}}}ka();if(t(L)&&t(L.VENDOR)){b=L.VENDOR;for(var I in b)if(b.hasOwnProperty(I))switch(I){case "membrana":la(b[I])}}})}n(L.BEFORE_SCRIPT)?ma(a):a()}
function ma(a){var b=L.BEFORE_SCRIPT;b+=parseInt(Date.now()/864E5,10);F(b,ca,function(){ea=!0;a.call(null)},a)}function ja(a){var b=n(L.GPT_ID)&&"null"!==L.GPT_ID?H+"?id="+L.GPT_ID+(L.GPT_DATA_LAYER?"&l=dataLayer":""):H;window.googletag&&!0===window.googletag.apiReady?a():F(b,ca,function(){da=!0;a.call(null)},na)}function oa(a){var b=document.createElement("div");C(b,"api-gpt-fixed-wrapper");b.style.position="relative";b.id=L.TYPE+"-"+G();a.appendChild(b);return b}
function pa(a,b){var c=document.createElement("div"),e=b&&b.close_color&&"string"===typeof b.close_color&&(3===b.close_color.length||6===b.close_color.length)?b.close_color:"FFF",f=b&&b.close_bg&&"string"===typeof b.close_bg&&(3===b.close_bg.length||6===b.close_bg.length)?b.close_bg:"000",g=r(f);b=b&&(b.close_bg_opacity||0===b.close_bg_opacity)&&0<=b.close_bg_opacity&&1>b.close_bg_opacity?b.close_bg_opacity:1;c.style.width="25px";c.style.height="25px";c.style.position="absolute";c.style.zIndex=(100001).toString();
c.style.top="-25px";c.style.right="0";c.style.cursor="pointer";c.style.backgroundColor=0<=b&&1>b?"rgba( "+g.r+", "+g.l+", "+g.b+", "+b+" )":"#"+f;C(c,"api-gpt-close-btn");c.innerHTML='<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 15 15" width="100%" height="100%" stroke="#'+e+'"><path d="M3.25,3.25l8.5,8.5M11.75,3.25l-8.5,8.5"></path></svg>';a.appendChild(c);return c}
function na(){var a=null;if(L.GPT&&"array"===v(L.GPT)&&0<L.GPT.length){a={};var b={},c;for(c in L.GPT){if(L.GPT.hasOwnProperty(c)&&n(L.GPT[c].id)&&n(L.GPT[c].path)&&L.GPT[c].size&&(null===L.GPT[c].size||t(J[L.GPT[c].size])||"array"===v(L.GPT[c].size)&&0<L.GPT[c].size.length)&&("string"===typeof L.GPT[c].size&&t(J[L.GPT[c].size])&&(L.GPT[c].size=J[L.GPT[c].size]),"string"===typeof L.GPT[c].mapping&&t(K[L.GPT[c].mapping])&&(L.GPT[c].mapping=K[L.GPT[c].mapping]),b.h=document.getElementById(L.GPT[c].id),
b.h)){L.GPT[c].node=b.h;!0===L.CLEAR_NODE&&B(b.h);if(ba(b.h)||b.h.hasAttribute("data-fixed")&&"true"===b.h.getAttribute("data-fixed"))L.GPT[c].parent=L.GPT[c].id,L.GPT[c].id=oa(b.h).id,b.h.style.display="none",L.GPT[c].remove=!0;if(L.GPT[c].bg){var e=null;0<=L.GPT[c].bg_opacity&&1>=L.GPT[c].bg_opacity&&(e=r(L.GPT[c].bg))?b.h.style.backgroundColor="rgba("+e.r+","+e.l+","+e.b+","+L.GPT[c].bg_opacity+")":b.h.style.backgroundColor=(-1===L.GPT[c].bg.indexOf("#")?"#":"")+L.GPT[c].bg}L.GPT[c].border&&(b.h.style.borderColor=
(-1===L.GPT[c].border.indexOf("#")?"#":"")+L.GPT[c].border,b.h.style.borderWidth="1px",b.h.style.borderStyle="solid");1!==L.GPT[c].close&&2!==L.GPT[c].close||pa(b.h,L.GPT[c]).addEventListener("click",function(f){return function(){A(f.h)}}(b));a[L.GPT[c].id]=L.GPT[c]}b={h:b.h}}}ha(a);return a}
function ka(){var a=null;if((a=na())&&t(a)){var b={},c;for(c in a)b.g=c,a.hasOwnProperty(b.g)&&window.googletag.cmd.push(function(f){return function(){var g=window.googletag.defineSlot(a[f.g].path,a[f.g].size,a[f.g].id);if(a[f.g].mapping&&y(a[f.g].mapping)){var p=window.googletag.sizeMapping(),q=!1,k;for(k in a[f.g].mapping)a[f.g].mapping.hasOwnProperty(k)&&y(a[f.g].mapping[k][0])&&y(a[f.g].mapping[k][1])&&(q=!0,p.addSize(a[f.g].mapping[k][0],a[f.g].mapping[k][1]));q&&g.defineSizeMapping(p.build())}if(a[f.g].targeting&&
"array"===v(a[f.g].targeting)&&1<=a[f.g].targeting.length)for(var l in a[f.g].targeting)a[f.g].targeting.hasOwnProperty(l)&&"string"===typeof a[f.g].targeting[l][0]&&("string"===typeof a[f.g].targeting[l][1]||y(a[f.g].targeting[l][1]))&&g.setTargeting(a[f.g].targeting[l][0],a[f.g].targeting[l][1]);g.addService(window.googletag.pubads())}}(b)),b={g:b.g};window.googletag.cmd.push(function(){qa(a)});window.googletag.cmd.push(function(){window.googletag.companionAds().setRefreshUnfilledSlots(!0);var f=
window.googletag.pubads();f.enableSingleRequest();f.enableAsyncRendering();f.collapseEmptyDivs();f.setCentering(!0);window.googletag.enableServices()});b={};for(var e in a)b.j=e,a.hasOwnProperty(b.j)&&window.googletag.cmd.push(function(f){return function(){window.googletag.display(a[f.j].id)}}(b)),b={j:b.j}}}
function la(a){if(t(a))for(var b in a)if(a.hasOwnProperty(b)&&n(a[b].id)&&t(a[b].options)){var c=document.getElementById(a[b].id),e=a[b].options;if(c&&n(e.id)){a=document.createElement("div");b=document.createElement("div");b.id=e.id;C(b,e["class"]);C(a,e.classWrapper);a.appendChild(b);c.appendChild(a);window.notsyCmd=window.notsyCmd||[];window.notsyCmd.push(function(){window.notsyInit({pageVersionAutodetect:!0})});break}}}
function qa(a){window.googletag.pubads().addEventListener("slotRenderEnded",function(b){W=!0;var c=b.slot.getSlotElementId();b=b.isEmpty;if(t(a[c])){var e=document.getElementById(a[c].parent||a[c].id);e&&!b?"none"===e.style.display&&(e.style.display="block"):e&&!1!==a[c].remove&&L.CLEAR_NODE&&A(e)}})}
if(L){if(t(L)&&t(L.GPT))for(var Y in L.GPT)if(L.GPT.hasOwnProperty(Y)&&"vendor"===L.GPT[Y].path&&t(L.GPT[Y].options)&&n(L.GPT[Y].options.vendor)){var ra=JSON.parse(JSON.stringify(L.GPT[Y])),Z=L.GPT[Y].options.vendor.toLowerCase();L.VENDOR=L.VENDOR||{};L.VENDOR[Z]=L.VENDOR[Z]||[];L.VENDOR[Z].push(ra);delete L.GPT[Y]}("array"===v(L.GPT)&&0<L.GPT.length||n(L.CLASS))&&ia()}; })();
